"""empty message

Revision ID: 65daf2256cbe
Create Date: 2018-09-28 01:54:19.514091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65daf2256cbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'attestation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'method',
            sa.Enum('PHONE', 'EMAIL', 'AIRBNB', 'FACEBOOK', 'TWITTER', name='attestationtypes'),
            nullable=True
        ),
        sa.Column('eth_address', sa.String(), nullable=True),
        sa.Column('value', sa.String(), nullable=True),
        sa.Column('signature', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'eth_notification_endpoint',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('eth_address', sa.String(length=255), nullable=True),
        sa.Column('device_token', sa.String(length=255), nullable=True),
        sa.Column('type', sa.Enum('APN', 'FCM', name='ethnotificationtypes'), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('verified', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_eth_notification_endpoint_device_token'),
        'eth_notification_endpoint',
        ['device_token'],
        unique=False
    )
    op.create_index(
        op.f('ix_eth_notification_endpoint_eth_address'),
        'eth_notification_endpoint',
        ['eth_address'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_eth_notification_endpoint_eth_address'),
        table_name='eth_notification_endpoint'
    )
    op.drop_index(
        op.f('ix_eth_notification_endpoint_device_token'),
        table_name='eth_notification_endpoint'
    )
    op.drop_table('eth_notification_endpoint')
    op.drop_table('attestation')
    # ### end Alembic commands ###
